Exclude arquillian-transaction-jta for tomee. Openejb have an own TransactionProvider. In this commit i exclude it in test pom, and introduce as a new dependency in every other test profile.
Exception fixed:
java.lang.IllegalStateException: Multiple service implementations found for interface org.jboss.arquillian.transaction.spi.provider.TransactionProvider. org.jboss.arquillian.transaction.jta.provider.JtaTransactionProvider, org.apache.openejb.arquillian.transaction.OpenEJBTransactionProvider
	at org.jboss.arquillian.core.impl.loadable.ServiceRegistryLoader.onlyOne(ServiceRegistryLoader.java:74)
	at org.jboss.arquillian.transaction.impl.lifecycle.TransactionHandler.getTransactionProvider(TransactionHandler.java:243)