upgrade shrinkwrap-resolver to 2.0.0-beta-2 arquillian-tomee-common have a transitive dependency to aether-:1.13.1 (through openejb-provisionning) wich conflicts with aether version used by shrinkwrap-resolver 1.0 . Results NoClassDefFoundError org.sonatype.aether.impl.SyncContextFactory at arquillian-tomee startup.